### ISSUE TITLE
missing LICENCE file

### ISSUE THREAD

**Issue by ingvagabund** [shurcooL/sanitized_anchor_name#1]
Hi,

sanitized_anchor_name has become a build dependency of kubernetes. I would like to package your awesome project into Fedora. Can I ask you for adding a LICENCE file? :) It would be great.

Thanks
Jan

**Comment by dmitshur** [comment]
Are you okay with [this license](https://github.com/shurcooL/License)?

**Comment by ingvagabund** [comment]
MIT licence is okay, thanks.
